# Docker Compose configuration for HTTP/API mode (default)
services:
  mcp-memory-service:
    build:
      context: ../..
      dockerfile: tools/docker/Dockerfile
    env_file:
      - ./.env
    ports:
      - "${HTTP_PORT:-8000}:8000"  # Host port can be changed via HTTP_PORT
    volumes:
      # Single data directory for all storage
      - ./data:/app/data
      - ./data/backups:/app/backups
      - ./data/sqlite_db:/app/sqlite_db

    environment:
      # Mode selection
      - MCP_MODE=${MCP_MODE:-mcp}

      # Storage configuration
      - MCP_MEMORY_STORAGE_BACKEND=${MCP_MEMORY_STORAGE_BACKEND}
      - MCP_MEMORY_SQLITE_PATH=${MCP_MEMORY_SQLITE_PATH}
      - MCP_MEMORY_BACKUPS_PATH=${MCP_MEMORY_BACKUPS_PATH}

      # Prefer ONNX embeddings in HTTP mode to avoid torch/HF downloads
      - MCP_MEMORY_USE_ONNX=${MCP_MEMORY_USE_ONNX}

      # HTTP configuration
      - MCP_HTTP_PORT=${MCP_HTTP_PORT:-8000}
      - MCP_HTTP_HOST=${MCP_HTTP_HOST}
      - MCP_API_KEY=${MCP_API_KEY:-your-secure-api-key-here}
      - MCP_CORS_ORIGINS=${MCP_CORS_ORIGINS:-*}
      - MCP_SSE_HEARTBEAT=${MCP_SSE_HEARTBEAT:-30}

      # Optional: HTTPS configuration
      # - MCP_HTTPS_ENABLED=true
      # - MCP_HTTPS_PORT=8443
      # - MCP_SSL_CERT_FILE=/app/certs/cert.pem
      # - MCP_SSL_KEY_FILE=/app/certs/key.pem

      # Performance tuning
      - LOG_LEVEL=${LOG_LEVEL:-INFO}

      # MCP Association configuration
      - MCP_ASSOCIATIONS_ENABLED=${MCP_ASSOCIATIONS_ENABLED}
      - MCP_ASSOCIATION_MIN_SIMILARITY=${MCP_ASSOCIATION_MIN_SIMILARITY}
      - MCP_ASSOCIATION_MAX_SIMILARITY=${MCP_ASSOCIATION_MAX_SIMILARITY}
      - MCP_ASSOCIATION_MAX_PAIRS=${MCP_ASSOCIATION_MAX_PAIRS}
      
      # Retrieve memory configuration
      - MCP_SIMILARITY_THRESHOLD=${MCP_SIMILARITY_THRESHOLD}

      # Python configuration
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src

    # Use the unified entrypoint
    entrypoint: ["/usr/local/bin/docker-entrypoint-unified.sh"]

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
