# Slim CPU-only deployment using ONNX embeddings (no torch)
# Usage:
#   MCP API mode: docker-compose -f docker-compose.slim.yml up -d

services:
  mcp-memory-service:
    build:
      context: ../..
      dockerfile: tools/docker/Dockerfile.slim
      args:
        SKIP_MODEL_DOWNLOAD: "true"   # set to "false" to prefetch ONNX model
    ports:
      - "${HTTP_PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
    environment:
      # HTTP mode
      - MCP_MODE=http
      - MCP_HTTP_HOST=${MCP_HTTP_HOST}
      - MCP_HTTP_PORT=${MCP_HTTP_PORT:-8000}
      - MCP_API_KEY=${MCP_API_KEY:-your-secure-api-key-here}

      # Storage configuration: sqlite-vec recommended in slim
      - MCP_MEMORY_STORAGE_BACKEND=sqlite_vec
      - MCP_MEMORY_SQLITE_PATH=/app/data/sqlite_vec.db
      - MCP_MEMORY_BACKUPS_PATH=/app/data/backups

      # Enable ONNX (no torch) path
      - MCP_MEMORY_USE_ONNX=1

      # Logging/perf
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app/src

    entrypoint: ["/usr/local/bin/docker-entrypoint-unified.sh"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
